# Generated by Django 4.2.6 on 2023-11-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='brand',
            field=models.CharField(default='generico', max_length=50),
            preserve_default=False,
        ),
    ]
