# Generated by Django 4.2.6 on 2023-11-14 19:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0009_alter_producto_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
