# Generated by Django 4.2.6 on 2023-11-14 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_datosextra_avater'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datosextra',
            old_name='avater',
            new_name='avatar',
        ),
    ]
